name: release please

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: create release
        uses: googleapis/release-please-action@v4
        with:
          release-type: python