name: release please

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: create release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: python
      - name: compress tutorial cases
        run: tar -czvf everest-tutorials-drogon.tar.gz ./data/drogon
      - name: upload release artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} everest-tutorials-drogon.tar.gz
